# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    serializer:
        enabled: true
        default_context:
            enable_annotations: true
        mapping:
            paths: ['%kernel.project_dir%/config/serialization']
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
